11 спринт
JRaven13/java-filmorate pull request #7
Opened 2023-11-25 09:32 UTC by JRaven13

2023-11-26 06:54 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>  }
Нужно добавить обработку Throwable в 500ый статус

2023-11-26 06:57 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film changeFilm(@Valid @RequestBody Film film) {
В контролере фильмов нужно использовать `@Validated(Update.class)` 
```
	@PutMapping("/films")
	public Film update(@Validated(Update.class) @RequestBody final Film film) {
		log.info("Updating film {}", film);
		return service.update(film);
	}
```
PS 
Яндекс настаивает требовать

2023-11-26 07:01 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
filmStorage; должен быть полем сервиса. Схема взаимодействия следущая Контроллер->Сервис->Сторадж

2023-11-26 07:03 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      private final UserService userService;
Тоже самое как и у фильмов

2023-11-26 07:12 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Integer> likes;
Поля с лайками в фильме быть не должно

2023-11-26 07:15 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
>  public class InMemoryUserStorage implements UserStorage {
Все InMemory реализации нужно убрать из проекта

2023-11-26 07:16 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
>  public class InMemoryFilmStorage implements FilmStorage {
Нужно убрать из проекта

2023-11-26 07:19 UTC, VadimZharkov commented on src/main/resources/schema.sql
> +
Это таблица связки двух сущностей, поэтому идентификатор здесь избыточен, можно первичный ключ построить по двум колонкам  user_id  и  friend_id

2023-11-26 07:20 UTC, VadimZharkov commented on src/main/resources/schema.sql
> +
См коммент к friends

2023-11-26 07:22 UTC, VadimZharkov commented on src/main/resources/schema.sql
> +    like_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
См коммент к friends

2023-11-26 07:30 UTC, VadimZharkov commented
Нет картинки со схемой БД

2023-11-26 07:31 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Integer> friends;
Лишнее поле

2023-11-26 07:33 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +
Добавить методы по работе с фильмами

2023-11-26 07:34 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +
Добавить методы по работе с юзерами

2023-11-26 07:37 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        SqlRowSet filmRows = jdbcTemplate.queryForRowSet("SELECT film_id, name, description, release_date," +
В запрос нужно добавить JOIN с mpa чтобы далее в цикле не происходило обращение к БД (mpaDbStorage.getMpa(filmRows.getInt("rating_mpa_id"))). Всегда где возможно нужно стараться избегать доп. запросов, если можно обойтись без этого.

2023-11-26 07:41 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        while (filmRows.next()) {
цикл не нужен в явном виде. далее был создан метод mapRowToFilm им и нужно воспользоваться
 jdbcTemplate.query("select * ...", FilmDbStorage::mapRowToFilm);

2023-11-26 07:44 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        film.getGenres().forEach(g -> {
Добавлять в цикле по одному запросу не есть хорошо для производительности.
Лучше воспользоваться пакетной вставкой. Посмотри и примени здесь jdbcTemplate.batchUpdate

2023-11-26 07:46 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sqlQuery = "INSERT INTO likes (film_id, user_id) VALUES(?, ?)";
Эту задачу лучше поручить LikeDbStorage, а здесь просто вызвать метод

2023-11-26 07:46 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sqlQuery = "DELETE FROM likes WHERE film_id = ? AND user_id = ?";
См коммент выше

2023-11-26 07:49 UTC, VadimZharkov requested changes
Нужно исправить замечания

2023-11-26 11:31 UTC, JRaven13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>  }
+

2023-11-26 11:37 UTC, JRaven13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film changeFilm(@Valid @RequestBody Film film) {
50/50

2023-11-26 11:48 UTC, JRaven13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
+

2023-11-26 11:54 UTC, JRaven13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      private final UserService userService;
50/50

2023-11-26 11:55 UTC, JRaven13 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Integer> likes;
+

2023-11-26 11:57 UTC, JRaven13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
>  public class InMemoryUserStorage implements UserStorage {
+

2023-11-26 11:57 UTC, JRaven13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
>  public class InMemoryFilmStorage implements FilmStorage {
+

2023-11-26 11:58 UTC, JRaven13 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +
+

2023-11-26 11:58 UTC, JRaven13 commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +
+

2023-11-26 13:44 UTC, JRaven13 commented on src/main/resources/schema.sql
> +
+

2023-11-26 13:44 UTC, JRaven13 commented on src/main/resources/schema.sql
> +
+

2023-11-26 13:44 UTC, JRaven13 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Integer> friends;
+

2023-11-26 13:52 UTC, JRaven13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        while (filmRows.next()) {
50/50

2023-11-26 14:12 UTC, JRaven13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        film.getGenres().forEach(g -> {
Не знаю как переделать

2023-11-26 14:21 UTC, JRaven13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sqlQuery = "INSERT INTO likes (film_id, user_id) VALUES(?, ?)";
Вроде так

2023-11-27 16:25 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>  }
Не сделано

2023-11-27 16:30 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        film.getGenres().forEach(g -> {
Пример
```
private void saveGenres(Film film) {
		final Long filmId = film.getId();
		jdbcTemplate.update("delete from FILM_GENRES where FILM_ID = ?", filmId);
		final Set<Genre> genres = film.getGenres();
		if (genres == null || genres.isEmpty()) {
			return;
		}
		final ArrayList<Genre> genreList = new ArrayList<>(genres);
		jdbcTemplate.batchUpdate(
				"insert into FILM_GENRES (FILM_ID, GENRE_ID) values (?, ?)",
				new BatchPreparedStatementSetter() {
					public void setValues(PreparedStatement ps, int i) throws SQLException {
						ps.setLong(1, filmId);
						ps.setLong(2, genreList.get(i).getId());
					}

					public int getBatchSize() {
						return genreList.size();
					}
				});
	}
```

2023-11-27 17:00 UTC, JRaven13 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        SqlRowSet filmRows = jdbcTemplate.queryForRowSet("SELECT film_id, name, description, release_date," +
Пожалуйста я очень устал =)

2023-11-27 17:28 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>  }
```
@ExceptionHandler
	@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public ErrorResponse handleThrowable(final Throwable e) {
		log.info("500 {}", e.getMessage(), e);
		return new ErrorResponse(e.getMessage());
	}
```

2023-11-27 17:29 UTC, VadimZharkov requested changes
Насчет обработчика ошибок, добавить
```
	@ExceptionHandler
	@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public ErrorResponse handleThrowable(final Throwable e) {
		log.info("500 {}", e.getMessage(), e);
		return new ErrorResponse(e.getMessage());
	}

```

2023-11-27 18:05 UTC, JRaven13 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>  }
свой логер сделать?

2023-11-28 05:45 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>  }
конечно)

2023-11-28 05:52 UTC, VadimZharkov requested changes
Добьем уже с хендлером ошибок. Понятно что и в остальные его методы логирование нужно добавить)

2023-11-28 12:26 UTC, VadimZharkov approved these changes

2023-11-28 14:52 UTC, merged